language: node_js
sudo: required 

services:
- docker

node_js:
- "8"

install:
- npm install

script:
- docker run --rm -d -p 8545:8545 foamspace/cliquebait:latest && sleep 30
- truffle migrate
- truffle test 
