language: node_js
dist: trusty
sudo: false

node_js:
- "6"

install:
- npm install -g aira-deploy ethereumjs-testrpc

script:
- aira-deploy --abi
- testrpc >/dev/null & (sleep 5 && node tests/daofund_test.js && node tests/association_test.js)

cache:
  directories:
  - .cache
