language: node_js
sudo: false

node_js:
- "6"

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

install:
- npm install -g aira-deploy ethereumjs-testrpc

script:
- aira-deploy --abi
- testrpc >/dev/null & (sleep 5 && node tests/daofund_test.js && node tests/association_test.js)

cache:
  directories:
  - .cache
